// Auto-generated by mic_ai.tools.export_id_ref_lut_c
// Source: C:/mic_theory/.tmp_pytest/pytest-of-11lis/pytest-0/test_export_id_ref_lut_c0/id_ref_lut.json
#ifndef TEST_ID_REF_LUT_H
#define TEST_ID_REF_LUT_H

#include <stdint.h>
#include <stddef.h>

#define TEST_OMEGA_SCALE 1024
#define TEST_LOAD_SCALE 1024
#define TEST_ID_SCALE 1024
#define TEST_OMEGA_SIZE 2
#define TEST_LOAD_SIZE 2

static const int32_t test_omega_grid_q[2] = {
  1024, 2048,
};

static const int32_t test_load_grid_q[2] = {
  102, 205,
};

static const int16_t test_id_ref_table_q[4] = {
  512, 614,
  717, 819,
};

static inline size_t test_upper_index(const int32_t *grid, size_t n, int32_t value) {
  if (n == 0) { return 0; }
  if (value <= grid[0]) { return 0; }
  for (size_t i = 1; i < n; ++i) {
    if (value <= grid[i]) { return i; }
  }
  return n - 1;
}

static inline int16_t test_id_ref_query_q(int32_t omega_q, int32_t load_q) {
  const size_t o_hi = test_upper_index(test_omega_grid_q, TEST_OMEGA_SIZE, omega_q);
  const size_t l_hi = test_upper_index(test_load_grid_q, TEST_LOAD_SIZE, load_q);
  const size_t o_lo = (o_hi == 0) ? 0 : (o_hi - 1);
  const size_t l_lo = (l_hi == 0) ? 0 : (l_hi - 1);

  const int32_t o0 = test_omega_grid_q[o_lo];
  const int32_t o1 = test_omega_grid_q[o_hi];
  const int32_t l0 = test_load_grid_q[l_lo];
  const int32_t l1 = test_load_grid_q[l_hi];

  const size_t idx00 = o_lo * TEST_LOAD_SIZE + l_lo;
  const size_t idx10 = o_hi * TEST_LOAD_SIZE + l_lo;
  const size_t idx01 = o_lo * TEST_LOAD_SIZE + l_hi;
  const size_t idx11 = o_hi * TEST_LOAD_SIZE + l_hi;

  const int16_t v00 = test_id_ref_table_q[idx00];
  const int16_t v10 = test_id_ref_table_q[idx10];
  const int16_t v01 = test_id_ref_table_q[idx01];
  const int16_t v11 = test_id_ref_table_q[idx11];

  if (o1 == o0 && l1 == l0) {
    return v00;
  }

  const int32_t one = 1 << 15;
  int32_t t = 0;
  int32_t u = 0;
  if (o1 != o0) {
    t = (int32_t)(((int64_t)(omega_q - o0) << 15) / (int64_t)(o1 - o0));
  }
  if (l1 != l0) {
    u = (int32_t)(((int64_t)(load_q - l0) << 15) / (int64_t)(l1 - l0));
  }

  const int64_t v0 = (((int64_t)(one - t) * v00) + ((int64_t)t * v10)) >> 15;
  const int64_t v1 = (((int64_t)(one - t) * v01) + ((int64_t)t * v11)) >> 15;
  const int64_t v = (((int64_t)(one - u) * v0) + ((int64_t)u * v1)) >> 15;
  return (int16_t)v;
}

static inline int16_t test_id_ref_query(float omega, float load) {
  const int32_t omega_q = (int32_t)(omega * TEST_OMEGA_SCALE);
  const int32_t load_q = (int32_t)(load * TEST_LOAD_SCALE);
  return test_id_ref_query_q(omega_q, load_q);
}

#endif
